app/Todo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.Home.as_view(),name="home"),
    path('admin/', admin.site.urls),
    path('test/', views.TestPage.as_view(),name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('task/',include("task.urls", namespace="task")),
    path('dashboard/', include("dashboard.urls", namespace="dashboard")),
    path('accounts/', include("django.contrib.auth.urls")),

]

app/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tasker</title>



    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'TodoApplication/css/master.css'%}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'fonts/ionicons.min.css'%}">

  </head>
  <body>
    <nav class="navbar navbar-dark navbar-expand-md bg-dark ">
        <div class="container-fluid"><a class="navbar-brand" href="/">Tasker</a><button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse"
                id="navcol-1">
              {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li class="nav-item" role="presentation"><a class="nav-link active" href="/dashboard">Dashborad</a></li>
                </ul>
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a></li>
                </ul>
                {% else %}
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'accounts:login' %}">login</a></li>
                      <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'accounts:signup'%}">Sign up</a></li>
                </ul>


                {% endif %}
            </div>
        </div>
    </nav>

    <div class="mycontent container-fluid">
      {% block content %}

      {% endblock %}

      <div class="footer-basic ">
          <footer>
              <div class="social  social-icon">
                <a class="" href="https://www.instagram.com/shadidamr/?hl=en" target="_blank"><i class="icon ion-social-instagram"></i></a>
                <a href="https://github.com/amrshadid" target="_blank"><i class="icon ion-social-github"></i></a>
                <a href="https://www.facebook.com/amr.shadeed" target="_blank"><i class="icon ion-social-facebook"></i></a>
              </div>
              <p class="copyright">Amr Shadid © 2020</p>
              <small  class="text-right form-text text-muted">made in love by Amr <i class="fa fa-heart"></i> </small>
          </footer>
      </div>
    <script src="{% static "js/jquery.min.js" %}" type="text/javascript" ></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}" type="text/javascript" ></script>
    <script src="{% static "TodoApplication/js/master.js" %}" type="text/javascript" ></script>
  </body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class="container p-4" >
    <h1 class="text-center display-3">Welcome to Tasker </h1>
    <hr>
    {% if user.is_authenticated %}
    <div class="container">
      <h3 class="display-4">Welcome {{user}}</h3>
      <a class="btn btn-primry btn-lg btn-primary" href="/dashboard">Go to dashboard</a>
    </div>
    <hr>
    {%else%}
    <div class="container">
      <h3 class="text-center display-4">The idea</h3>
      <p class="font-italic">A system that manages tasks where more than one task board can be created, and each panel has a board manager who can add employees and share their tasks, and can modify the list of people allowed to see the board, as there is in each panel a task gallery where the task is opened and begins within the queue to move manually through one Employees to the list of "in progress" until the end, and each task has a special page that allows employees to add their comment on that task and print the job that can be modified in terms of content and status and until it is permanently deleted from the database</p>
    </div>
    {% endif %}
    </div>

{% endblock %}

app/templates/test.html
{% extends "base.html" %}
{% block content %}

{% endblock %}

app/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}